### ISSUE TITLE
Permohonan untuk menerjemahkan

### ISSUE THREAD

**Issue by yuyuart** [progit2-ms/progit2#11]
Saya dari Indonesia - Nanggro Aceh Darussalam, saya sangat tertarik dengan proyek anda dan ingin berkontribusi dengan baik dalam proyek anda, apakah saya di izinkan untuk menerjemahkannya di proyek anda,. salam

**Comment by plokmi** [comment]
Thank you for your interest, sorry to say I would prefer someone who speaks Malay as their mother tongue to be part of the team. There are lots of words which may be found in Indonesian but are not really found in Malay, specifically, the words 'proyek', 'berkontribusi' and 'menerjemahkannya' which you are using.
